baseURL = "https://aldidoanta.github.io"
defaultContentLanguage = "en"
languageCode = "en"
title = "Aldi Doanta"
theme = "uBlogger"

[params]
version = "2.0.X"
# site description
description = "Personal Blog of Aldi Doanta"
# site default theme ("light", "dark", "auto")
defaultTheme = "auto"
# date format
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
images = ["images/logo.jpg"]

  # Home page config
  [params.home]
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "aldidkurnia@gmail.com"
      # title shown in home page (HTML format is supported)
      title = "Hello, I'm Aldi Doanta"
      # subtitle shown in home page
      subtitle = "\"For a cause worth fighting for\""
      # whether to show social links
      social = true

  # Page config
  [params.page]
    [params.page.toc]
      # whether to enable the table of the contents
      enable = false

  # Social config about the author
  [params.social]
    GitHub = "aldidoanta"
    LinkedIn = "aldidoanta"
    Medium = "@aldidoanta"
    GitLab = "aldidkurnia"
    Keybase = "aldidoanta"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false
